BITFINEX = 'bitfinex'
COINONE = 'coinone'
BITHUMB = 'bithumb'
POLONIX = 'polonix'
BITTREX = 'bittrex'

MARKETS = [
    BITFINEX, COINONE, BITHUMB, POLONIX, BITTREX
]

AVAILABLE_MARKETS = [
    BITFINEX, BITHUMB,
]
